-- GENERATED from screen_items.json. Numeric screening items (v1.2); our own wording, no instrument text.
begin;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$adult:face_overall$s$, $s$adult$s$, $s$appearance.overall$s$, $s$facial$s$, $s$How happy are you with how your face looks overall?$s$, $s$¿Qué tan satisfecho/a está con cómo se ve su cara en general?$s$, $s$Very unhappy$s$, $s$Very happy$s$, $s$Muy insatisfecho/a$s$, $s$Muy satisfecho/a$s$, 1, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$adult:face_eyes$s$, $s$adult$s$, $s$appearance.eyes$s$, $s$facial$s$, $s$How happy are you with how your eyes look?$s$, $s$¿Qué tan satisfecho/a está con cómo se ven sus ojos?$s$, $s$Very unhappy$s$, $s$Very happy$s$, $s$Muy insatisfecho/a$s$, $s$Muy satisfecho/a$s$, 2, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$adult:face_nose$s$, $s$adult$s$, $s$appearance.nose$s$, $s$facial$s$, $s$How happy are you with how your nose looks?$s$, $s$¿Qué tan satisfecho/a está con cómo se ve su nariz?$s$, $s$Very unhappy$s$, $s$Very happy$s$, $s$Muy insatisfecho/a$s$, $s$Muy satisfecho/a$s$, 3, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$adult:face_lips$s$, $s$adult$s$, $s$appearance.lips$s$, $s$facial$s$, $s$How happy are you with how your lips and mouth look?$s$, $s$¿Qué tan satisfecho/a está con cómo se ven sus labios y boca?$s$, $s$Very unhappy$s$, $s$Very happy$s$, $s$Muy insatisfecho/a$s$, $s$Muy satisfecho/a$s$, 4, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$adult:face_cheeks$s$, $s$adult$s$, $s$appearance.cheeks$s$, $s$facial$s$, $s$How happy are you with how your cheeks look?$s$, $s$¿Qué tan satisfecho/a está con cómo se ven sus mejillas?$s$, $s$Very unhappy$s$, $s$Very happy$s$, $s$Muy insatisfecho/a$s$, $s$Muy satisfecho/a$s$, 5, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$adult:face_chin$s$, $s$adult$s$, $s$appearance.chin_jawline$s$, $s$facial$s$, $s$How happy are you with your chin and jawline?$s$, $s$¿Qué tan satisfecho/a está con su mentón y su mandíbula?$s$, $s$Very unhappy$s$, $s$Very happy$s$, $s$Muy insatisfecho/a$s$, $s$Muy satisfecho/a$s$, 6, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$adult:face_skin$s$, $s$adult$s$, $s$appearance.skin$s$, $s$facial$s$, $s$How happy are you with the skin on your face?$s$, $s$¿Qué tan satisfecho/a está con la piel de su cara?$s$, $s$Very unhappy$s$, $s$Very happy$s$, $s$Muy insatisfecho/a$s$, $s$Muy satisfecho/a$s$, 7, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$adult:face_smile$s$, $s$adult$s$, $s$appearance.smile_teeth$s$, $s$facial$s$, $s$How happy are you with your smile and teeth?$s$, $s$¿Qué tan satisfecho/a está con su sonrisa y sus dientes?$s$, $s$Very unhappy$s$, $s$Very happy$s$, $s$Muy insatisfecho/a$s$, $s$Muy satisfecho/a$s$, 8, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$adult:soc_confidence$s$, $s$adult$s$, $s$psych.self_confidence$s$, $s$social$s$, $s$How confident do you feel in yourself day to day?$s$, $s$¿Qué tan seguro/a de sí mismo/a se siente en el día a día?$s$, $s$Not at all$s$, $s$Completely$s$, $s$Nada$s$, $s$Totalmente$s$, 9, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$adult:soc_mood$s$, $s$adult$s$, $s$psych.mood$s$, $s$social$s$, $s$How has your mood been lately?$s$, $s$¿Cómo ha estado su ánimo últimamente?$s$, $s$Very low$s$, $s$Very good$s$, $s$Muy bajo$s$, $s$Muy bueno$s$, 10, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$adult:soc_comfort$s$, $s$adult$s$, $s$social.comfort$s$, $s$social$s$, $s$How comfortable are you meeting people or being in a group?$s$, $s$¿Qué tan cómodo/a se siente al conocer gente o estar en grupo?$s$, $s$Not at all$s$, $s$Completely$s$, $s$Nada$s$, $s$Totalmente$s$, 11, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$adult:soc_joining$s$, $s$adult$s$, $s$social.avoidance$s$, $s$social$s$, $s$How free do you feel to join in photos, video calls and going out?$s$, $s$¿Qué tan libre se siente para salir en fotos, videollamadas y salir de casa?$s$, $s$I avoid them$s$, $s$Completely free$s$, $s$Los evito$s$, $s$Totalmente libre$s$, 12, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$adult:soc_thoughts$s$, $s$adult$s$, $s$distress.preoccupation$s$, $s$social$s$, $s$How easy is it to stop thinking about how your face looks?$s$, $s$¿Qué tan fácil le resulta dejar de pensar en cómo se ve su cara?$s$, $s$Very hard$s$, $s$Very easy$s$, $s$Muy difícil$s$, $s$Muy fácil$s$, 13, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$adult:soc_hiding$s$, $s$adult$s$, $s$distress.hiding$s$, $s$social$s$, $s$How comfortable are you being seen without covering or hiding parts of your face?$s$, $s$¿Qué tan cómodo/a se siente al ser visto/a sin cubrir ni ocultar partes de su cara?$s$, $s$Not at all$s$, $s$Completely$s$, $s$Nada$s$, $s$Totalmente$s$, 14, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$adult:fn_breathing$s$, $s$adult$s$, $s$function.breathing$s$, $s$function$s$, $s$How easy is it to breathe through your nose?$s$, $s$¿Qué tan fácil le resulta respirar por la nariz?$s$, $s$Very hard$s$, $s$Very easy$s$, $s$Muy difícil$s$, $s$Muy fácil$s$, 15, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$adult:fn_eating$s$, $s$adult$s$, $s$function.eating_drinking$s$, $s$function$s$, $s$How easy is eating and drinking?$s$, $s$¿Qué tan fácil le resulta comer y beber?$s$, $s$Very hard$s$, $s$Very easy$s$, $s$Muy difícil$s$, $s$Muy fácil$s$, 16, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$adult:fn_speaking$s$, $s$adult$s$, $s$function.speaking$s$, $s$function$s$, $s$How easy is it to speak and be understood?$s$, $s$¿Qué tan fácil le resulta hablar y que le entiendan?$s$, $s$Very hard$s$, $s$Very easy$s$, $s$Muy difícil$s$, $s$Muy fácil$s$, 17, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$adult:fn_expression$s$, $s$adult$s$, $s$function.facial_expression$s$, $s$function$s$, $s$How easily can you make facial expressions (smile, frown, close your eyes)?$s$, $s$¿Con qué facilidad puede hacer expresiones faciales (sonreír, fruncir el ceño, cerrar los ojos)?$s$, $s$Very hard$s$, $s$Very easy$s$, $s$Muy difícil$s$, $s$Muy fácil$s$, 18, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$adult:fn_pain$s$, $s$adult$s$, $s$adverse.pain_discomfort$s$, $s$function$s$, $s$How free of pain or discomfort is your face?$s$, $s$¿Qué tan libre de dolor o molestias está su cara?$s$, $s$Constant pain$s$, $s$No pain at all$s$, $s$Dolor constante$s$, $s$Sin dolor$s$, 19, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$adult:fn_sensation$s$, $s$adult$s$, $s$adverse.numbness_sensation$s$, $s$function$s$, $s$How normal does the feeling (sensation) in your face seem?$s$, $s$¿Qué tan normal siente la sensibilidad de su cara?$s$, $s$Very different$s$, $s$Completely normal$s$, $s$Muy distinta$s$, $s$Totalmente normal$s$, 20, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$pediatric:face_overall$s$, $s$pediatric$s$, $s$appearance.overall$s$, $s$facial$s$, $s$How happy are you with how your face looks?$s$, $s$¿Qué tan contento/a estás con cómo se ve tu cara?$s$, $s$Very unhappy$s$, $s$Very happy$s$, $s$Muy descontento/a$s$, $s$Muy contento/a$s$, 1, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$pediatric:face_eyes$s$, $s$pediatric$s$, $s$appearance.eyes$s$, $s$facial$s$, $s$How happy are you with how your eyes look?$s$, $s$¿Qué tan contento/a estás con cómo se ven tus ojos?$s$, $s$Very unhappy$s$, $s$Very happy$s$, $s$Muy descontento/a$s$, $s$Muy contento/a$s$, 2, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$pediatric:face_nose$s$, $s$pediatric$s$, $s$appearance.nose$s$, $s$facial$s$, $s$How happy are you with how your nose looks?$s$, $s$¿Qué tan contento/a estás con cómo se ve tu nariz?$s$, $s$Very unhappy$s$, $s$Very happy$s$, $s$Muy descontento/a$s$, $s$Muy contento/a$s$, 3, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$pediatric:face_lips$s$, $s$pediatric$s$, $s$appearance.lips$s$, $s$facial$s$, $s$How happy are you with how your lips look?$s$, $s$¿Qué tan contento/a estás con cómo se ven tus labios?$s$, $s$Very unhappy$s$, $s$Very happy$s$, $s$Muy descontento/a$s$, $s$Muy contento/a$s$, 4, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$pediatric:face_ears$s$, $s$pediatric$s$, $s$appearance.ears$s$, $s$facial$s$, $s$How happy are you with how your ears look?$s$, $s$¿Qué tan contento/a estás con cómo se ven tus orejas?$s$, $s$Very unhappy$s$, $s$Very happy$s$, $s$Muy descontento/a$s$, $s$Muy contento/a$s$, 5, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$pediatric:face_chin$s$, $s$pediatric$s$, $s$appearance.chin_jawline$s$, $s$facial$s$, $s$How happy are you with your chin and jaw?$s$, $s$¿Qué tan contento/a estás con tu mentón y tu mandíbula?$s$, $s$Very unhappy$s$, $s$Very happy$s$, $s$Muy descontento/a$s$, $s$Muy contento/a$s$, 6, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$pediatric:face_skin$s$, $s$pediatric$s$, $s$appearance.skin$s$, $s$facial$s$, $s$How happy are you with the skin on your face?$s$, $s$¿Qué tan contento/a estás con la piel de tu cara?$s$, $s$Very unhappy$s$, $s$Very happy$s$, $s$Muy descontento/a$s$, $s$Muy contento/a$s$, 7, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$pediatric:face_smile$s$, $s$pediatric$s$, $s$appearance.smile_teeth$s$, $s$facial$s$, $s$How happy are you with your smile and teeth?$s$, $s$¿Qué tan contento/a estás con tu sonrisa y tus dientes?$s$, $s$Very unhappy$s$, $s$Very happy$s$, $s$Muy descontento/a$s$, $s$Muy contento/a$s$, 8, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$pediatric:soc_confidence$s$, $s$pediatric$s$, $s$psych.self_confidence$s$, $s$social$s$, $s$How good do you feel about yourself most days?$s$, $s$¿Qué tan bien te sientes contigo mismo/a la mayoría de los días?$s$, $s$Not good$s$, $s$Really good$s$, $s$Nada bien$s$, $s$Muy bien$s$, 9, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$pediatric:soc_mood$s$, $s$pediatric$s$, $s$psych.mood$s$, $s$social$s$, $s$How happy have you been feeling lately?$s$, $s$¿Qué tan feliz te has sentido últimamente?$s$, $s$Very sad$s$, $s$Very happy$s$, $s$Muy triste$s$, $s$Muy feliz$s$, 10, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$pediatric:soc_comfort$s$, $s$pediatric$s$, $s$social.comfort$s$, $s$social$s$, $s$How comfortable are you around other kids?$s$, $s$¿Qué tan cómodo/a te sientes con otros niños y niñas?$s$, $s$Not at all$s$, $s$Completely$s$, $s$Nada$s$, $s$Totalmente$s$, 11, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$pediatric:soc_school$s$, $s$pediatric$s$, $s$social.school$s$, $s$social$s$, $s$How well are things going at school?$s$, $s$¿Qué tan bien van las cosas en la escuela?$s$, $s$Really badly$s$, $s$Really well$s$, $s$Muy mal$s$, $s$Muy bien$s$, 12, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$pediatric:soc_teasing$s$, $s$pediatric$s$, $s$social.teasing_comments$s$, $s$social$s$, $s$How free are you from teasing or comments about your face?$s$, $s$¿Qué tan libre estás de burlas o comentarios sobre tu cara?$s$, $s$It happens a lot$s$, $s$It never happens$s$, $s$Pasa mucho$s$, $s$Nunca pasa$s$, 13, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$pediatric:soc_thoughts$s$, $s$pediatric$s$, $s$distress.preoccupation$s$, $s$social$s$, $s$How easy is it to stop thinking about how your face looks?$s$, $s$¿Qué tan fácil te resulta dejar de pensar en cómo se ve tu cara?$s$, $s$Very hard$s$, $s$Very easy$s$, $s$Muy difícil$s$, $s$Muy fácil$s$, 14, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$pediatric:fn_breathing$s$, $s$pediatric$s$, $s$function.breathing$s$, $s$function$s$, $s$How easy is it to breathe through your nose?$s$, $s$¿Qué tan fácil te resulta respirar por la nariz?$s$, $s$Very hard$s$, $s$Very easy$s$, $s$Muy difícil$s$, $s$Muy fácil$s$, 15, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$pediatric:fn_eating$s$, $s$pediatric$s$, $s$function.eating_drinking$s$, $s$function$s$, $s$How easy is eating and drinking?$s$, $s$¿Qué tan fácil te resulta comer y beber?$s$, $s$Very hard$s$, $s$Very easy$s$, $s$Muy difícil$s$, $s$Muy fácil$s$, 16, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$pediatric:fn_speaking$s$, $s$pediatric$s$, $s$function.speaking$s$, $s$function$s$, $s$How easy is it to talk and be understood?$s$, $s$¿Qué tan fácil te resulta hablar y que te entiendan?$s$, $s$Very hard$s$, $s$Very easy$s$, $s$Muy difícil$s$, $s$Muy fácil$s$, 17, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$pediatric:fn_expression$s$, $s$pediatric$s$, $s$function.facial_expression$s$, $s$function$s$, $s$How easily can you smile, frown and close your eyes?$s$, $s$¿Con qué facilidad puedes sonreír, fruncir el ceño y cerrar los ojos?$s$, $s$Very hard$s$, $s$Very easy$s$, $s$Muy difícil$s$, $s$Muy fácil$s$, 18, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$pediatric:fn_pain$s$, $s$pediatric$s$, $s$adverse.pain_discomfort$s$, $s$function$s$, $s$How free of pain or soreness is your face?$s$, $s$¿Qué tan libre de dolor o molestias está tu cara?$s$, $s$Hurts a lot$s$, $s$Doesn't hurt$s$, $s$Duele mucho$s$, $s$No duele$s$, 19, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
insert into public.screen_items (id, population, construct_id, domain, text_en, text_es, low_en, high_en, low_es, high_es, sort_order, active)
values ($s$pediatric:fn_scars$s$, $s$pediatric$s$, $s$adverse.scarring$s$, $s$function$s$, $s$How happy are you with any scars on your face?$s$, $s$¿Qué tan contento/a estás con las cicatrices de tu cara, si tienes?$s$, $s$Very unhappy$s$, $s$Very happy$s$, $s$Muy descontento/a$s$, $s$Muy contento/a$s$, 20, true)
on conflict (id) do update set population=excluded.population, construct_id=excluded.construct_id, domain=excluded.domain, text_en=excluded.text_en, text_es=excluded.text_es, low_en=excluded.low_en, high_en=excluded.high_en, low_es=excluded.low_es, high_es=excluded.high_es, sort_order=excluded.sort_order, active=true;
commit;
