#!/bin/bash
# Builds the web app for hosting from the `app` edge function and embeds the output into
# supabase/functions/app/bundle.ts (generated, gitignored). Then: supabase functions deploy app
set -euo pipefail
cd "$(dirname "$0")/.."
export VITE_BASE_PATH=/functions/v1/app/
(cd web && npm run build --silent)
python3 - <<'PY'
import base64, json, mimetypes, os
mimetypes.add_type("application/javascript", ".js"); mimetypes.add_type("application/manifest+json", ".webmanifest")
root = "web/dist"; files = {}
for dp, _, fns in os.walk(root):
    for fn in fns:
        p = os.path.join(dp, fn); rel = "/" + os.path.relpath(p, root).replace(os.sep, "/")
        if rel == "/404.html": continue  # GitHub Pages trick; the function does SPA fallback itself
        files[rel] = {"t": mimetypes.guess_type(p)[0] or "application/octet-stream", "b": base64.b64encode(open(p, "rb").read()).decode()}
out = "// GENERATED by scripts/build-app.sh — do not edit.\nexport const FILES: Record<string, { t: string; b: string }> = " + json.dumps(files) + ";\n"
open("supabase/functions/app/bundle.ts", "w").write(out)
print(f"embedded {len(files)} files, {sum(len(v['b']) for v in files.values())//1024} KB base64")
PY
